"""
Embed textbook chunks and upload to Qdrant vector database.

This script reads the chunks generated by chunk_textbook.py,
creates embeddings using OpenAI's text-embedding-3-small model,
and uploads them to Qdrant Cloud for retrieval.
"""

import os
import sys
import json
from pathlib import Path
from typing import List, Dict
import uuid

# Add backend to path to import utilities
script_dir = Path(__file__).parent
project_root = script_dir.parent
sys.path.insert(0, str(project_root / 'backend'))

from utils.openai_client import create_embedding
from utils.vector_store import init_collection, insert_embeddings, get_collection_info
from qdrant_client.models import PointStruct


def create_point_from_chunk(chunk: Dict, chunk_id: int) -> tuple:
    """
    Create a Qdrant point from a chunk with its embedding.

    Args:
        chunk: Chunk dictionary with text and metadata
        chunk_id: Unique ID for this chunk

    Returns:
        Tuple of (PointStruct, token_count)
    """
    # Create embedding for the chunk text
    embedding = create_embedding(chunk['chunk_text'], model="text-embedding-ada-002")

    # Create payload with metadata
    payload = {
        'chapter_id': chunk['chapter_id'],
        'chapter_title': chunk['chapter_title'],
        'part': chunk['part'],
        'chunk_index': chunk['chunk_index'],
        'chunk_text': chunk['chunk_text'],
        'chunk_token_count': chunk['chunk_token_count'],
    }

    # Create point
    point = PointStruct(
        id=chunk_id,
        vector=embedding,
        payload=payload
    )

    return point, chunk['chunk_token_count']


def batch_embed_and_upload(chunks: List[Dict], batch_size: int = 10):
    """
    Embed chunks in batches and upload to Qdrant.

    Args:
        chunks: List of chunk dictionaries
        batch_size: Number of chunks to process per batch (default: 10)
    """
    total_chunks = len(chunks)
    total_tokens = 0

    print(f"\n🔄 Embedding and uploading {total_chunks} chunks in batches of {batch_size}...")

    for i in range(0, total_chunks, batch_size):
        batch = chunks[i:i + batch_size]
        batch_num = (i // batch_size) + 1
        total_batches = (total_chunks + batch_size - 1) // batch_size

        print(f"\nBatch {batch_num}/{total_batches} (chunks {i+1}-{min(i+batch_size, total_chunks)}):")

        points = []
        for j, chunk in enumerate(batch):
            chunk_id = i + j
            try:
                point, token_count = create_point_from_chunk(chunk, chunk_id)
                points.append(point)
                total_tokens += token_count

                print(f"  ✓ Embedded: {chunk['chapter_id']} [chunk {chunk['chunk_index']}]")

            except Exception as e:
                print(f"  ✗ Error embedding chunk {chunk_id}: {e}")
                continue

        # Upload batch to Qdrant
        if points:
            try:
                insert_embeddings(points)
                print(f"  📤 Uploaded {len(points)} points to Qdrant")
            except Exception as e:
                print(f"  ✗ Error uploading batch: {e}")

    return total_tokens


def main():
    """Main function to embed all chunks and upload to Qdrant."""
    # Load chunks from JSON
    chunks_file = project_root / 'scripts' / 'textbook_chunks.json'

    if not chunks_file.exists():
        print(f"Error: Chunks file not found at {chunks_file}")
        print("Please run chunk_textbook.py first to generate chunks.")
        return

    print("📖 Loading chunks...")
    with open(chunks_file, 'r', encoding='utf-8') as f:
        chunks = json.load(f)

    print(f"✅ Loaded {len(chunks)} chunks")

    # Initialize Qdrant collection
    print("\n🔧 Initializing Qdrant collection...")
    try:
        init_collection()
        print("✅ Collection ready")
    except Exception as e:
        print(f"✗ Error initializing collection: {e}")
        return

    # Embed and upload chunks
    total_tokens = batch_embed_and_upload(chunks, batch_size=10)

    # Get collection info
    try:
        collection_info = get_collection_info()
        print(f"\n✅ Embedding complete!")
        print(f"\n📊 Collection Statistics:")
        print(f"  Total vectors: {collection_info.points_count}")
        print(f"  Vector dimension: {collection_info.config.params.vectors.size}")
        print(f"  Distance metric: {collection_info.config.params.vectors.distance}")

        print(f"\n💰 Embedding Cost Estimate:")
        print(f"  Total tokens embedded: {total_tokens:,}")
        print(f"  Estimated cost (text-embedding-ada-002 at $0.0001/1K tokens): ${(total_tokens / 1_000) * 0.0001:.4f}")

    except Exception as e:
        print(f"Warning: Could not retrieve collection info: {e}")


if __name__ == "__main__":
    main()
